//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnMentor.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vnMentor.Resources.HomePageResource", typeof(HomePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An Account.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET Web Application.
        /// </summary>
        public static string ASPNETMVCWebApplication {
            get {
                return ResourceManager.GetString("ASPNETMVCWebApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bootstrap HTML Website Templates.
        /// </summary>
        public static string BootstrapHTMLWebsiteTemplates {
            get {
                return ResourceManager.GetString("BootstrapHTMLWebsiteTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detailed Documentation.
        /// </summary>
        public static string DetailedDocumentation {
            get {
                return ResourceManager.GetString("DetailedDocumentation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Envato Portfolio.
        /// </summary>
        public static string EnvatoPortfolio {
            get {
                return ResourceManager.GetString("EnvatoPortfolio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, it&apos;s in our plan, but for now, we couldn&apos;t guarantee the release time..
        /// </summary>
        public static string FAQFourAnswer {
            get {
                return ResourceManager.GetString("FAQFourAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can you create a .NET Core MVC version?.
        /// </summary>
        public static string FAQFourQuestion {
            get {
                return ResourceManager.GetString("FAQFourQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We only provide support for fixing existing bugs in the templates and answering questions regarding the existing features. Step-by-step guidance on how to do your custom modifications, how to solve bugs after your own modifications and direct installation are not part of our support. Thank you so much for your understanding. We will spend our time to create more amazing templates for you..
        /// </summary>
        public static string FAQOneAnswer {
            get {
                return ResourceManager.GetString("FAQOneAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How is the support policy?.
        /// </summary>
        public static string FAQOneQuestion {
            get {
                return ResourceManager.GetString("FAQOneQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, you can. Go to &quot;/Views/Shared/_FooterBeforeLogin.cshtml&quot; and find the footer section to edit or remove the copyright text..
        /// </summary>
        public static string FAQThreeAnswer {
            get {
                return ResourceManager.GetString("FAQThreeAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can I edit or remove the Copyright text at the footer?.
        /// </summary>
        public static string FAQThreeQuestion {
            get {
                return ResourceManager.GetString("FAQThreeQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Answer is: Immediately after purchase..
        /// </summary>
        public static string FAQTwoAnswerPartOne {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to for more information, there is “Downloading your items” section at the end of this article..
        /// </summary>
        public static string FAQTwoAnswerPartTwo {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When can I download the file after purchase the item?.
        /// </summary>
        public static string FAQTwoQuestion {
            get {
                return ResourceManager.GetString("FAQTwoQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatic regrading.
        /// </summary>
        public static string Feature10 {
            get {
                return ResourceManager.GetString("Feature10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If a teacher selects the wrong answer as the correct one and discovers this after the students have taken the exam, their results will be re-graded automatically if they want to change the answer..
        /// </summary>
        public static string Feature10Description {
            get {
                return ResourceManager.GetString("Feature10Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyze Chart.
        /// </summary>
        public static string Feature11 {
            get {
                return ResourceManager.GetString("Feature11", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Charts to analyze results, questions that most students answered incorrectly, and more..
        /// </summary>
        public static string Feature11Description {
            get {
                return ResourceManager.GetString("Feature11Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Strict rules.
        /// </summary>
        public static string Feature12 {
            get {
                return ResourceManager.GetString("Feature12", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot skip questions. Cannot copy the question text while taking the exam..
        /// </summary>
        public static string Feature12Description {
            get {
                return ResourceManager.GetString("Feature12Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System admin can create, update and delete users. Students and teachers can register an account by themselves too..
        /// </summary>
        public static string Feature1Description {
            get {
                return ResourceManager.GetString("Feature1Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store question bank.
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save your question bank and re-use it in different exams with different mark distributions..
        /// </summary>
        public static string Feature2Description {
            get {
                return ResourceManager.GetString("Feature2Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule exam.
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can save an exam now and schedule it to start later. Then, publish an exam when it is ready to be announced to the students..
        /// </summary>
        public static string Feature3Description {
            get {
                return ResourceManager.GetString("Feature3Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Students&apos; result.
        /// </summary>
        public static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Students&apos; results can be exported to Excel or PDF. You can also sort the result list by student score to see the top students in the exam..
        /// </summary>
        public static string Feature4Description {
            get {
                return ResourceManager.GetString("Feature4Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import questions.
        /// </summary>
        public static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can create questions in batches by importing them from Excel..
        /// </summary>
        public static string Feature5Description {
            get {
                return ResourceManager.GetString("Feature5Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import users.
        /// </summary>
        public static string Feature6 {
            get {
                return ResourceManager.GetString("Feature6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can create user accounts in batches by importing them from Excel..
        /// </summary>
        public static string Feature6Description {
            get {
                return ResourceManager.GetString("Feature6Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomize question.
        /// </summary>
        public static string Feature7 {
            get {
                return ResourceManager.GetString("Feature7", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can choose to randomise or un-randomize the question order of an exam. Randomizing questions can prevent cheating because students cannot discuss the answers as they are getting different questions at one time..
        /// </summary>
        public static string Feature7Description {
            get {
                return ResourceManager.GetString("Feature7Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Release answer.
        /// </summary>
        public static string Feature8 {
            get {
                return ResourceManager.GetString("Feature8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can choose to release or unrelease the answers to the questions. Before the answers are released, students will get their results but will not be able to see the correct answers. We recommend releasing the answer only after all the students have taken the exam..
        /// </summary>
        public static string Feature8Description {
            get {
                return ResourceManager.GetString("Feature8Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export result.
        /// </summary>
        public static string Feature9 {
            get {
                return ResourceManager.GetString("Feature9", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Students&apos; result can be exported to excel or pdf..
        /// </summary>
        public static string Feature9Description {
            get {
                return ResourceManager.GetString("Feature9Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features1 {
            get {
                return ResourceManager.GetString("Features1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vnMentor Contains Full Essential Features To Conduct An Exam..
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill your details to register..
        /// </summary>
        public static string Fillyourdetailstoregister {
            get {
                return ResourceManager.GetString("Fillyourdetailstoregister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill your username and password to sign in..
        /// </summary>
        public static string Fillyourusernameandpasswordtosignin {
            get {
                return ResourceManager.GetString("Fillyourusernameandpasswordtosignin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Follow our social media to get updates or news about the projects..
        /// </summary>
        public static string FollowUsDescription {
            get {
                return ResourceManager.GetString("FollowUsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vnMentor is an online exam system that delivers exam management, question bank management, automated grading, an analytical dashboard, and more..
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Revolutionize how you evaluate your students.
        /// </summary>
        public static string HomeTitleOne {
            get {
                return ResourceManager.GetString("HomeTitleOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomeTitleTwo {
            get {
                return ResourceManager.GetString("HomeTitleTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import &amp; Export.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vnMentor FAQ Articles.
        /// </summary>
        public static string NetStarterFAQArticles {
            get {
                return ResourceManager.GetString("NetStarterFAQArticles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register &amp; Login.
        /// </summary>
        public static string RegisterAndLogin {
            get {
                return ResourceManager.GetString("RegisterAndLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending Email.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the following article.
        /// </summary>
        public static string TheFollowingArticle {
            get {
                return ResourceManager.GetString("TheFollowingArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To vnMentor.
        /// </summary>
        public static string TovnMentor {
            get {
                return ResourceManager.GetString("TovnMentor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vnMentor.
        /// </summary>
        public static string WebAppTitle {
            get {
                return ResourceManager.GetString("WebAppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After Purchasing, You Will Get A Zip File Which Contains The Following.
        /// </summary>
        public static string WhatyougetDescription {
            get {
                return ResourceManager.GetString("WhatyougetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save your question bank and re-use it in different exams with different mark distributions..
        /// </summary>
        public static string WhyUs1Description {
            get {
                return ResourceManager.GetString("WhyUs1Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reusable Questions.
        /// </summary>
        public static string WhyUs1Title {
            get {
                return ResourceManager.GetString("WhyUs1Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Say goodbye to the hassle of paper-based exams and the time-consuming manual grading system..
        /// </summary>
        public static string WhyUs2Description {
            get {
                return ResourceManager.GetString("WhyUs2Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Your Time.
        /// </summary>
        public static string WhyUs2Title {
            get {
                return ResourceManager.GetString("WhyUs2Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Streamline your examination process. Create exam, select questions from question bank, allocate marks, done!.
        /// </summary>
        public static string WhyUs3Description {
            get {
                return ResourceManager.GetString("WhyUs3Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Simple Process.
        /// </summary>
        public static string WhyUs3Title {
            get {
                return ResourceManager.GetString("WhyUs3Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomizing Question Order, Scheduling Exam Start Date &amp; Time, Storing Your Question Bank, And More..
        /// </summary>
        public static string WhyUsDescription {
            get {
                return ResourceManager.GetString("WhyUsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Why vnMentor.
        /// </summary>
        public static string WhyUsTitle {
            get {
                return ResourceManager.GetString("WhyUsTitle", resourceCulture);
            }
        }
    }
}
