//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnMentor.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vnMentor.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        public static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to already exists..
        /// </summary>
        public static string alreadyexists {
            get {
                return ResourceManager.GetString("alreadyexists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An Account.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Anerroroccurred {
            get {
                return ResourceManager.GetString("Anerroroccurred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you Sure To Delete This Record?.
        /// </summary>
        public static string AreyouSureToDeleteThisRecord {
            get {
                return ResourceManager.GetString("AreyouSureToDeleteThisRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By default, system admin can manage this module, while normal user does not have permission to view/add/edit/delete this module..
        /// </summary>
        public static string ByDefaultSystemAdminCanManageWhileNormalUserCant {
            get {
                return ResourceManager.GetString("ByDefaultSystemAdminCanManageWhileNormalUserCant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Password For User.
        /// </summary>
        public static string ChangePasswordForUser {
            get {
                return ResourceManager.GetString("ChangePasswordForUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click to see error detail..
        /// </summary>
        public static string Clicktoseeerrordetail {
            get {
                return ResourceManager.GetString("Clicktoseeerrordetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Columns count mismatch..
        /// </summary>
        public static string ColumnsCountMismatch {
            get {
                return ResourceManager.GetString("ColumnsCountMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        public static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Confirm Password field is required..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Country field is required..
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Profile Picture:.
        /// </summary>
        public static string CurrentProfilePicture {
            get {
                return ResourceManager.GetString("CurrentProfilePicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By default, system admin can view a dashboard regarding all users&apos; data, while normal user can only view a dashboard regarding their own data..
        /// </summary>
        public static string DashboardRolePermissionDescription {
            get {
                return ResourceManager.GetString("DashboardRolePermissionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, demo account cannot be deleted..
        /// </summary>
        public static string DemoAccountCannotBeDeleted {
            get {
                return ResourceManager.GetString("DemoAccountCannotBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Attachments:.
        /// </summary>
        public static string EditAttachments {
            get {
                return ResourceManager.GetString("EditAttachments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit My Profile.
        /// </summary>
        public static string EditMyProfile {
            get {
                return ResourceManager.GetString("EditMyProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit User Attachment.
        /// </summary>
        public static string EditUserAttachment {
            get {
                return ResourceManager.GetString("EditUserAttachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address already taken. Please try again with other Email Address..
        /// </summary>
        public static string EmailAddressTaken {
            get {
                return ResourceManager.GetString("EmailAddressTaken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the details.
        /// </summary>
        public static string EnterTheDetails {
            get {
                return ResourceManager.GetString("EnterTheDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExporttoExcel {
            get {
                return ResourceManager.GetString("ExporttoExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export to Pdf.
        /// </summary>
        public static string ExporttoPdf {
            get {
                return ResourceManager.GetString("ExporttoPdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed due to exception error..
        /// </summary>
        public static string FailedExceptionError {
            get {
                return ResourceManager.GetString("FailedExceptionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed. Only jpg, jpeg and png file can be set as Profile Picture..
        /// </summary>
        public static string FailedOnlyJpgJpegPngCanBeSetAsProfilePicture {
            get {
                return ResourceManager.GetString("FailedOnlyJpgJpegPngCanBeSetAsProfilePicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password..
        /// </summary>
        public static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File URL.
        /// </summary>
        public static string FileURL {
            get {
                return ResourceManager.GetString("FileURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill in your email address, and we will send you a link to reset your password..
        /// </summary>
        public static string FillInEmailAddressWeWillSendYouResetPasswordLink {
            get {
                return ResourceManager.GetString("FillInEmailAddressWeWillSendYouResetPasswordLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill your username and password to sign in..
        /// </summary>
        public static string FillInYourUsernameAndPasswordToSignIn {
            get {
                return ResourceManager.GetString("FillInYourUsernameAndPasswordToSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill your details to register..
        /// </summary>
        public static string FillYourDetailsToRegister {
            get {
                return ResourceManager.GetString("FillYourDetailsToRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full Address.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NetStarter- ASP.NET MVC C# Web Application Starter Template.
        /// </summary>
        public static string HomeIndexTabTitle {
            get {
                return ResourceManager.GetString("HomeIndexTabTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID Card Number.
        /// </summary>
        public static string IDCardNumber {
            get {
                return ResourceManager.GetString("IDCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import From Excel.
        /// </summary>
        public static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importing Data From Excel... Please Wait....
        /// </summary>
        public static string ImportingDataFromExcelPleaseWait {
            get {
                return ResourceManager.GetString("ImportingDataFromExcelPleaseWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import User From Excel.
        /// </summary>
        public static string ImportUserFromExcel {
            get {
                return ResourceManager.GetString("ImportUserFromExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please download the excel template below and insert your user data. Please don&apos;t edit or add extra columns. Extra columns will be ignored while importing data. After completing insert your data in the excel file, save it and upload it through the upload section below..
        /// </summary>
        public static string ImportUserFromExcelDescription {
            get {
                return ResourceManager.GetString("ImportUserFromExcelDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters, including at least one uppercase letter, one lowercase letter, one digit, and one symbol..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Phone Number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Postal Code..
        /// </summary>
        public static string InvalidPostalCode {
            get {
                return ResourceManager.GetString("InvalidPostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username is invalid. Username must have at least 3 characters, must start with a letter, and cannot have special symbols..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Columns are invalid. Please use the provided template (UserExcelTemplate.xlsx) and make sure the columns are not removed or edited..
        /// </summary>
        public static string InvalidUserTemplate {
            get {
                return ResourceManager.GetString("InvalidUserTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of Roles.
        /// </summary>
        public static string ListofRoles {
            get {
                return ResourceManager.GetString("ListofRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of User Attachments.
        /// </summary>
        public static string ListofUserAttachments {
            get {
                return ResourceManager.GetString("ListofUserAttachments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of User Attachment Types.
        /// </summary>
        public static string ListofUserAttachmentTypes {
            get {
                return ResourceManager.GetString("ListofUserAttachmentTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        public static string ListofUsers {
            get {
                return ResourceManager.GetString("ListofUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of User Status.
        /// </summary>
        public static string ListofUserStatus {
            get {
                return ResourceManager.GetString("ListofUserStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List Of User With.
        /// </summary>
        public static string ListOfUserWith {
            get {
                return ResourceManager.GetString("ListOfUserWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string Lockedout {
            get {
                return ResourceManager.GetString("Lockedout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login Date Time.
        /// </summary>
        public static string LoginDateTime {
            get {
                return ResourceManager.GetString("LoginDateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login History.
        /// </summary>
        public static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By default, system admin can view all users&apos; login histories, while normal user can only view their own login histories..
        /// </summary>
        public static string LoginHistoryRolePermissionDescription {
            get {
                return ResourceManager.GetString("LoginHistoryRolePermissionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Attachments For:.
        /// </summary>
        public static string ManageAttachmentsFor {
            get {
                return ResourceManager.GetString("ManageAttachmentsFor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage User Attachment.
        /// </summary>
        public static string ManageUserAttachment {
            get {
                return ResourceManager.GetString("ManageUserAttachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum length allowed is 100 characters..
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum length allowed is 128 characters..
        /// </summary>
        public static string MaxLength128 {
            get {
                return ResourceManager.GetString("MaxLength128", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum length allowed is 256 characters..
        /// </summary>
        public static string MaxLength256 {
            get {
                return ResourceManager.GetString("MaxLength256", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The field must be at least 6 characters long..
        /// </summary>
        public static string MinLength6 {
            get {
                return ResourceManager.GetString("MinLength6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string ModifiedOn {
            get {
                return ResourceManager.GetString("ModifiedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Most of the users are with this status..
        /// </summary>
        public static string MostOfTheUsersAreWithThisStatus {
            get {
                return ResourceManager.GetString("MostOfTheUsersAreWithThisStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vnMentor.
        /// </summary>
        public static string NetStarter {
            get {
                return ResourceManager.GetString("NetStarter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation new password do not match..
        /// </summary>
        public static string NewPasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Normal user and system admin roles cannot be deleted or edited. because they will be used to determine the loading of login histories (Admin can see all users&apos; login histories, but a normal user can only see their own history)..
        /// </summary>
        public static string NormalUserSystemAdminCannotBeDeleted {
            get {
                return ResourceManager.GetString("NormalUserSystemAdminCannotBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not allowed to change password for demo account. Please sign up other account to try this feature..
        /// </summary>
        public static string NotAllowToChangePasswordForDemoAccount {
            get {
                return ResourceManager.GetString("NotAllowToChangePasswordForDemoAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note: System information can only be edited by System Admin..
        /// </summary>
        public static string NoteSystemInformation {
            get {
                return ResourceManager.GetString("NoteSystemInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not found or mismatch..
        /// </summary>
        public static string notfoundormismatch {
            get {
                return ResourceManager.GetString("notfoundormismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers are allowed..
        /// </summary>
        public static string OnlyLettersAndNumbers {
            get {
                return ResourceManager.GetString("OnlyLettersAndNumbers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only numbers are allowed..
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oops..
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong..
        /// </summary>
        public static string OopsSomethingwrong {
            get {
                return ResourceManager.GetString("OopsSomethingwrong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string outof {
            get {
                return ResourceManager.GetString("outof", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page 0 of Page 0.
        /// </summary>
        public static string Page0OfPage0 {
            get {
                return ResourceManager.GetString("Page0OfPage0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully!.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least 6 characters. Requires at least one Uppercase letter, one Lowercase letter, one Digit, and one Symbol..
        /// </summary>
        public static string PasswordRequirementText {
            get {
                return ResourceManager.GetString("PasswordRequirementText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in the following..
        /// </summary>
        public static string Pleasefillinthefollowing {
            get {
                return ResourceManager.GetString("Pleasefillinthefollowing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please go to Web.config and insert connectionString value to run this web application..
        /// </summary>
        public static string PleaseInsertConnectionString {
            get {
                return ResourceManager.GetString("PleaseInsertConnectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please Select....
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select all the files that you want to upload..
        /// </summary>
        public static string Pleaseselectallthefilesthatyouwanttoupload {
            get {
                return ResourceManager.GetString("Pleaseselectallthefilesthatyouwanttoupload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select an excel file..
        /// </summary>
        public static string Pleaseselectanexcelfile {
            get {
                return ResourceManager.GetString("Pleaseselectanexcelfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Profile Picture attachment type cannot be edited or deleted. Because it is used to validate whether a file uploaded by the user can be selected as a profile picture..
        /// </summary>
        public static string ProfilePictureAttachmentTypeCannotBeEditedOrDeleted {
            get {
                return ResourceManager.GetString("ProfilePictureAttachmentTypeCannotBeEditedOrDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully!.
        /// </summary>
        public static string RecordDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RecordDeletedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully!.
        /// </summary>
        public static string RecordSavedSuccessfully {
            get {
                return ResourceManager.GetString("RecordSavedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Records imported successfully!.
        /// </summary>
        public static string RecordsImportedSuccessfully {
            get {
                return ResourceManager.GetString("RecordsImportedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to records uploaded.
        /// </summary>
        public static string recordsuploaded {
            get {
                return ResourceManager.GetString("recordsuploaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registered user status cannot be deleted or edited. Because it&apos;s default status to assign to the registered user..
        /// </summary>
        public static string RegisteredUserStatusCannotBeDeletedOrEdited {
            get {
                return ResourceManager.GetString("RegisteredUserStatusCannotBeDeletedOrEdited", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register success! Please login now..
        /// </summary>
        public static string RegisterSuccessLoginNow {
            get {
                return ResourceManager.GetString("RegisterSuccessLoginNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove selected file(s).
        /// </summary>
        public static string Removeselectedfile {
            get {
                return ResourceManager.GetString("Removeselectedfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset password email sent successfully!.
        /// </summary>
        public static string ResetPasswordEmailSent {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role by Number of Users.
        /// </summary>
        public static string RolebyNumberofUsers {
            get {
                return ResourceManager.GetString("RolebyNumberofUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The role name already exist in the system..
        /// </summary>
        public static string RoleNameAlreadyExist {
            get {
                return ResourceManager.GetString("RoleNameAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role Permission for.
        /// </summary>
        public static string RolePermissionfor {
            get {
                return ResourceManager.GetString("RolePermissionfor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Role field is required..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchDot {
            get {
                return ResourceManager.GetString("SearchDot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an image file.
        /// </summary>
        public static string SelectAnImageFile {
            get {
                return ResourceManager.GetString("SelectAnImageFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select multiple....
        /// </summary>
        public static string Selectmultiple {
            get {
                return ResourceManager.GetString("Selectmultiple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show 10 Records.
        /// </summary>
        public static string Show10Records {
            get {
                return ResourceManager.GetString("Show10Records", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show 25 Records.
        /// </summary>
        public static string Show25Records {
            get {
                return ResourceManager.GetString("Show25Records", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show 50 Records.
        /// </summary>
        public static string Show50Records {
            get {
                return ResourceManager.GetString("Show50Records", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string Showing0Entries {
            get {
                return ResourceManager.GetString("Showing0Entries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some required* fields are empty. Please fill in all the required* fields..
        /// </summary>
        public static string SomeRequiredFieldsAreEmpty {
            get {
                return ResourceManager.GetString("SomeRequiredFieldsAreEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Status field is required..
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The errors are as below:.
        /// </summary>
        public static string Theerrorsareasbelow {
            get {
                return ResourceManager.GetString("Theerrorsareasbelow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Thisaccounthasbeenlockedout {
            get {
                return ResourceManager.GetString("Thisaccounthasbeenlockedout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone! Other related records will also be affected..
        /// </summary>
        public static string Thiscannotbeundone {
            get {
                return ResourceManager.GetString("Thiscannotbeundone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This role has the least number of user, perhaps it&apos;s a role with top permission..
        /// </summary>
        public static string ThisRoleHasTheLeastNumberOfUser {
            get {
                return ResourceManager.GetString("ThisRoleHasTheLeastNumberOfUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To vnMentor.
        /// </summary>
        public static string TovnMentor {
            get {
                return ResourceManager.GetString("TovnMentor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top Role.
        /// </summary>
        public static string TopRole {
            get {
                return ResourceManager.GetString("TopRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top Status.
        /// </summary>
        public static string TopStatus {
            get {
                return ResourceManager.GetString("TopStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total file size cannot be larger than 50MB..
        /// </summary>
        public static string TotalFileSizeCannotBeLargerThan50MB {
            get {
                return ResourceManager.GetString("TotalFileSizeCannotBeLargerThan50MB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total number of roles in the system..
        /// </summary>
        public static string TotalNumberOfRolesInTheSystem {
            get {
                return ResourceManager.GetString("TotalNumberOfRolesInTheSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total number of users in the system..
        /// </summary>
        public static string TotalNumberOfUsersInTheSystem {
            get {
                return ResourceManager.GetString("TotalNumberOfUsersInTheSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Roles.
        /// </summary>
        public static string TotalRoles {
            get {
                return ResourceManager.GetString("TotalRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type to Search....
        /// </summary>
        public static string TypetoSearch {
            get {
                return ResourceManager.GetString("TypetoSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Error.
        /// </summary>
        public static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploaded By.
        /// </summary>
        public static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploaded On.
        /// </summary>
        public static string UploadedOn {
            get {
                return ResourceManager.GetString("UploadedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Excel.
        /// </summary>
        public static string UploadExcel {
            get {
                return ResourceManager.GetString("UploadExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload User Attachment.
        /// </summary>
        public static string UploadUserAttachment {
            get {
                return ResourceManager.GetString("UploadUserAttachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Attachment.
        /// </summary>
        public static string UserAttachment {
            get {
                return ResourceManager.GetString("UserAttachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Attachment Type.
        /// </summary>
        public static string UserAttachmentType {
            get {
                return ResourceManager.GetString("UserAttachmentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user attachment type name already exist in the system..
        /// </summary>
        public static string UserAttachmentTypeNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserAttachmentTypeNameAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User by Status Chart.
        /// </summary>
        public static string UserbyStatusChart {
            get {
                return ResourceManager.GetString("UserbyStatusChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username already taken. Please try again with other username..
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User does not exist in the system..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users In The Role Of.
        /// </summary>
        public static string UsersInTheRoleOf {
            get {
                return ResourceManager.GetString("UsersInTheRoleOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Status.
        /// </summary>
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user status name already exist in the system..
        /// </summary>
        public static string UserStatusNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserStatusNameAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View List.
        /// </summary>
        public static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Role.
        /// </summary>
        public static string ViewRole {
            get {
                return ResourceManager.GetString("ViewRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View roles.
        /// </summary>
        public static string Viewroles {
            get {
                return ResourceManager.GetString("Viewroles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View this role.
        /// </summary>
        public static string Viewthisrole {
            get {
                return ResourceManager.GetString("Viewthisrole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View User.
        /// </summary>
        public static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View users.
        /// </summary>
        public static string Viewusers {
            get {
                return ResourceManager.GetString("Viewusers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View user status.
        /// </summary>
        public static string Viewuserstatus {
            get {
                return ResourceManager.GetString("Viewuserstatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete It!.
        /// </summary>
        public static string YesDeleteIt {
            get {
                return ResourceManager.GetString("YesDeleteIt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to access this page..
        /// </summary>
        public static string YouDontHavePermissionToAccess {
            get {
                return ResourceManager.GetString("YouDontHavePermissionToAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Password.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully!.
        /// </summary>
        public static string YourPasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordResetSuccessfully", resourceCulture);
            }
        }
    }
}
